### ISSUE TITLE
Bugged (and duplicated) spawns across maps

### ISSUE THREAD

**Issue by vegax87** [aura-project/melia#14]
#Steps to reproduce this bug:

1) Go to "Some Npc"  (a.k.a THAT NPC) in West Siauliai Woods and use /spawn monsterID nearby ( you can spawn whatever do you like)
2) Go to the border between West Siauliai Woods and Klaipeda, exactly where you see the green arrow on the ground
3) You will be teleported in a random zone of Klaipeda and the custom Hair Stylist and Stat Resetter NPCs are missing in the southern part of Klaipedia.
4) Now go to the upper left zone of Klaipedia ( above Central Plaza) and you will see again "THAT Npc" and the monster you spawned before...

**Comment by exectails** [comment]
I've ran back and forth a few times, with and without spawning something, but I couldn't reproduce this. Did you do anything else?

**Comment by vegax87** [comment]
Check my video: https://www.youtube.com/watch?v=sBzldNLGFpQ

the only thing I've done is to extract warps from ies.ipf with your IPF Browser but I don't know if the extraction corrupted the file or not.

ChannelServer log:

------------------------------------------------------------------------------
02/04/2016 17:06:59 [Debug] - PacketHandler: No handler found for '0D33', CZ_MAP_REVEAL_INFO.
------------------------------------------------------------------------------
Op: 0D33 CZ_MAP_REVEAL_INFO, Size: 152 (Table: 146, Garbage: 6)
------------------------------------------------------------------------------
0000   33 0D D8 01 00 00 75 03  00 00 FD 03 00 00 00 18   3.....u.........
0010   3E FF F8 FF 1F 18 00 00  00 00 00 00 00 00 00 00   >...............
0020   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0030   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0040   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0050   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0060   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0070   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0080   00 00 00 00 00 00 00 00  00 00 00 00 00 00 AB AA   ................
0090   26 42 65 88 82 3E 48 9F                            &Be..>H.
------------------------------------------------------------------------------

**Comment by huenato** [comment]
Same issue here
<img src="http://puu.sh/o3qIR/69eba46417.jpg"/>

**Comment by phstudy** [comment]
I also have this issue. The root cause is that client failed to warp to correct map. It can be verified by `/where` command.

**Comment by exectails** [comment]
>The root cause is that client failed to warp to correct map

Yea, that was my theory as well. Question now is why I can't reproduce it and why the server doesn't send the correct data. You are seeing the correct map after all, but the NPC/monster data the server sends is incorrect.

When warping a character, its new map id is set and after 3 more packets the client closes the connection to connect to the next zone server. When a connection is closed, the character is saved, incl. the new map id. When they connect to the next server, the map id is read and they're placed there.

This could happen if the client re-connects before the character is saved I guess. If that's the problem, we have to save the character from `FinalizeWarp`, right before the re-connect.

**Comment by exectails** [comment]
Could one of you test the above hot-fix?

**Comment by phstudy** [comment]
ok, I will test it.

**Comment by phstudy** [comment]
@exectails it works!

**Comment by vegax87** [comment]
it works!
