### ISSUE TITLE
 The login box has the login area and password, but lists the official servers, what to do?

### ISSUE THREAD

**Issue by gigantescu** [aura-project/melia#148]
https://ibb.co/egB3Fx
https://ibb.co/jaEZNc 
https://ibb.co/dLeOFx 

Help Me!

**Comment by exectails** [comment]
Try deleting the file "serverlist_recent.xml".

**Comment by rodrigo22021998** [comment]
after deleting the file "serverlist_recent.xml"
no server appears

**Comment by exectails** [comment]
The ServerListURL should end in `.cs` instead of `.xml`.
