### ISSUE TITLE
Where i can find client.xml?

### ISSUE THREAD

**Issue by GodLimbo** [aura-project/melia#150]
i need to change the values ServerListURL and StaticConfigURL on client.sml file.. but i can't find the xml file in melia-master folder.. thankyou

**Comment by exectails** [comment]
It's in your Tree of Savior client folder.

**Comment by GodLimbo** [comment]
where i can download the TOS full game? i mean the one that we can edit.. thankyou

**Comment by exectails** [comment]
Steam.

**Comment by GodLimbo** [comment]
is there any other option? because TOS from my region was blocked

**Comment by exectails** [comment]
Not really, no. I'm not aware of anyone creating mirrors.

**Comment by GodLimbo** [comment]
ok thanks dude.. maybe if someone open this thread and know the mirror please share the link here.. Thank you
