### ISSUE TITLE
Script variable system

### ISSUE THREAD

**Issue by exectails** [aura-project/melia#16]
We need to be able to carry information across multiple NPC and playing sessions, namely temporary and permanent character, account, and global variables. This could be as simple as a `var` function in Lua, that gets or sets a variable, based on the parameters.

```lua
local name = var("name")
if name == nil then
	msg("Who are you?")
	name = input("Please put in your name.")
	var("name", name)
end

msg("Hi, " .. name .. "!")
```
```lua
local timesVisited = var("visitedNpcXy")
timesVisited = var("visitedNpcXy", timesVisited + 1)
msg("This is visit number " .. timesVisited .. ".")
```

Given the fact that many of us will be familiar with eAthena, I propose we use the same prefixes to differentiate between variable types. [http://buwinow5.tripod.com/#Variables and scope](http://buwinow5.tripod.com/#Variables and scope)

**Comment by S-anasol** [comment]
you were *athena dev? :)

**Comment by greenboxal** [comment]
AthenaScript is a really bad designed scripting language. I don't think we should use this as it makes pretty easy to write flaky scripts.

We should have a proper session/global variable manager which the script should have access.

**Comment by exectails** [comment]
Oh, I agree, AthenaScript is pretty bad, and I didn't suggest that we use it in any way =P But somehow we have to specify whether a variable should be temporary, permanent, account or character based, and in a scripting environment you don't typically want lengthy calls, like

```csharp
GlobalVariableManager.SetPermanentCharacterVariable(characterId, "variableName", "foobar");
```

instead of

```lua
var("variableName", "foobar")
```

That's why I'm proposing prefixes for the variables, akin to the ones eAthena uses, for ease of use, and because some scripters will already be familiar with them.

**Comment by exectails** [comment]
Any objections? Anything you want to add, what might be needed, or that we have to look out for? Otherwise I'll probably add this soon.

**Comment by exectails** [comment]
Added in adb66fb8e434a1d10c3a223b7d8baa6fb299b0a6.
