### ISSUE TITLE
Password security

### ISSUE THREAD

**Issue by S-anasol** [aura-project/melia#25]
Wrap md5 into something more secure - [Blowfish?](https://en.wikipedia.org/wiki/Blowfish_(cipher))
Wrap coz client work with md5, but we can handle it on serverside as we want :+1:

**Comment by exectails** [comment]
In Aura we're wrapping the MD5 hash with BCrypt. However, Mabinogi is 10 years old, and it's unlikely the hash method will change at this point. If IMC decides not to use MD5 anymore, and we wrapped the hashes, servers might have to reset all passwords.

**Comment by S-anasol** [comment]
Thats not big pay for great security.

Coz servers db leaked too often. For example i have dozens of ragnarok databases with hundreds of thousands of accounts from currently working servers, coz all the use vulnerable site. 
Thats no good :smiling_imp: 
And md5 passwords can be easy revealed with rainbow tables.

Also working servers almost never update their emulators due many manual changes and other :)

**Comment by exectails** [comment]
Actually... Mabi did change the hashing as well a few years ago. They simply wrapped the MD5 hashes in SHA, which made them upgradeable. Thinking about it, they can't just switch to something else entirely, as that would invalidate their own hashes. Sorry^^

Yes, we should definitely do that, and I advocate for [BCrypt](https://codahale.com/how-to-safely-store-a-password/).
