### ISSUE TITLE
ChannelServer Error to Network Packet

### ISSUE THREAD

**Issue by AirShark** [aura-project/melia#35]
No handler found for '0D34', CZ_MAP_SEARCH_INFO and to many other error
[ChannelServer.txt](https://github.com/aura-project/melia/files/211191/ChannelServer.txt)

p.s. sorry my english

**Comment by exectails** [comment]
What you're seeing aren't errors, it's debug output, to inform developers about packets of information coming from the client, that the server doesn't handle yet. If you compile Melia in Release mode, you won't see those Debug messages.
