### ISSUE TITLE
Combat (Splash)

### ISSUE THREAD

**Issue by exectails** [aura-project/melia#36]
While combat range (#4) seems to be fixed now (it was the skill properties), splash damage isn't working yet. It presumably has a similar cause. The client sends only information about hitting a single enemy, no matter how many there are. The splash appears to be 0.

**Comment by Tachiorz** [comment]
Confirm. This is some of the skill properties as well. Haven't nailed which yet.

**Comment by Tachiorz** [comment]
Missing prop is SkillSR, skill.ies have string `광역 공격 비율 #{SkillSR}#` Greater Attack Rate? And a reference to:
```
function SCR_GET_SR_LV(skill)

	local pc = GetSkillOwner(skill);
	local value = pc.SR + skill.SklSR;
	
	if value < 1 then
	    value = 1
	end
	
	return value
	
end
```

**Comment by luismarcelovaf** [comment]
I'm pretty sure the "Greater Attack Rate" stands for what we know as "AoE Attack Ratio".
