### ISSUE TITLE
Characters HP, SP, Stamina

### ISSUE THREAD

**Issue by rincew1nd** [aura-project/melia#46]
Characters hp, sp and stamina values is pretty major functionality that we lack off. ATM it's not dynamic and can be changed only negatively (ZC_HIT_INFO & ZC_SKILL_HIT_INFO).

Characters max HP and SP values depends on:
- [ ] Any stats changes
  - [ ] Buffs (CON, MHP, MSP)
  - [ ] Items (Items on CON, SPR, HP, SP)
  - [x] Stats (CON, SPR)
- [x] Level UP (Level value)

Character current HP and SP values can be changed by:
- [x] Recovery (+HP, +SP | Firewood to faster recovery)
- [x] Damage dealt by enemy (- HP)
- [ ] Heal and Revive (+ HP, Resurrect)
- [ ] Skill cast (- SP)
- [ ] Debuff on character (Cancellation of HP restoring, ect)
- [ ] Consumable items
- [ ] Items stats (HP or SP recovery)

Characters zero HP and SP values trigger events like:
- [x] Death (zero HP)
- [ ] Inability to use spells (zero SP)
- [ ] Inability to run (zero Stamina)

Right now I'm working on this things. Here i will check what am I done so far.
Feel free to join me or suggest what I have forgot to mention.

**Comment by exectails** [comment]
Closing for now, since it hasn't been updated in over a year.
