### ISSUE TITLE
Warps

### ISSUE THREAD

**Issue by exectails** [aura-project/melia#5]
Everything to implement warps is in place, they just have to be added. Refer to the existing warps for reference and check the source to see how the addwarp function works.

https://github.com/aura-project/melia/blob/master/system/scripts/warps/f_siauliai_west.lua
https://github.com/aura-project/melia/blob/master/src/ChannelServer/Scripting/ScriptManager.cs#L427

The map names and coordinates can be taken from the `where` GM command, the warp name comes from the packets, but since it's just a name, I don't think they need to be official. The direction is the direction the warp arrow points to, with 0 being down.

![ss 2016-04-01 at 03 18 23](https://cloud.githubusercontent.com/assets/5593920/14207898/06bc0360-f81d-11e5-9f36-28cd109337a9.png)

**Comment by phstudy** [comment]
@exectails do you know where the direction information store?

**Comment by phstudy** [comment]
Do you consider using dx and dy directly instead of direction?
I think dx and dy are more intuitive, I just need to copy and paste.

**Comment by exectails** [comment]
Hum. I see your point. The reason I went with angles are custom NPCs, as cos and sin are definitely not intuitive if you don't have reference data. The official NPCs only have to be done once, but scripters will have to live with the system for far longer.

Maybe there's a way to do both? An overload? Or a function that generates the angle based on dx and dy? though that might get a little messy.

In MabiPale, the Pale for Mabinogi/Aura, we have an entity logger plugin, that lists all monsters and characters it can find in the packet list. It then shows their attributes and generates code for NPCs, that you can directly copy. We could create something similar for NPCs for PaleTree, that generates whatever we need. However, if the structure of ZC_ENTER_MONSTER changes, it would break the plugin for certain versions of the packet.

**Comment by phstudy** [comment]
I agree with your opinion. Angle is more intuitive when adding custom NPCs. I will try to port the MabiPale entity logger plugin to PaleTree.

I also leave the directionToDegree function here, for someone who try to convert them.
```
public static double directionToDegree(double x, double y)
{
	return Math.Atan2(y, x) * 57.2957795130823 + 45;
}
```

**Comment by exectails** [comment]
>I also leave the directionToDegree function here, for someone who try to convert them.

For convenience: http://aura-project.org/angle.htm

**Comment by phstudy** [comment]
I find that the `localKey` is difficult to parse and lookup from `maps.txt`. I have implemented the entity logger plugin for PaleTree, but it lacks the map `className`...

@exectails do you have any idea about the mapping?

Entity logger plugin for PaleTree: https://github.com/phstudy/PaleTree/commit/bd42edd1fd58392a91a11ea81ede59aed9593ff2

**Comment by exectails** [comment]
>I find that the localKey is difficult to parse and lookup from maps.txt.

What do you need it for?

**Comment by rincew1nd** [comment]
@exectails I have write a handy function to calculate entity rotation toward other entity (some try to implement basic monster AI). Maybe it will be helpfull.

```c#
public static World.Direction AngleBetweenTwoEntity(World.Position rotated, World.Position target)
{
    float dy = rotated.X - target.X;
    float dx = rotated.Z - target.Z;
    double angle = System.Math.Atan2(-dx, -dy) * 180.0 / System.Math.PI;
    return new World.Direction(
        (float)System.Math.Cos((angle / 180D) * System.Math.PI),
        (float)System.Math.Sin((angle / 180D) * System.Math.PI)
    );
}
```

**Comment by vegax87** [comment]
there's no need to calculate anything, the informations are already in the client:

see #24 and search every ID 40001, then copy his coordinates,direction and map name (you can comment it out with -- at the beginning of the line to prevent duplicated spawns)

use this warp list as reference to set the destinations: http://pastebin.com/raw/XkEYDE2Q

I give you an example how this works, yesterday @phstudy posted this screenshot: https://files.gitter.im/aura-project/melia/B230/packet_logger.PNG

these coordinates match exactly with this NPC: **addnpc(40001,"Gytis Settlement Area","c_Klaipe",240.6537,148.8095,895.663,109,"DummyCall")**

we just need to remove this spawn and use his data as reference for addwarp

**Comment by exectails** [comment]
The warps are all working now, yes?

**Comment by vegax87** [comment]
99% yes, except some of them that need to be activated with quest events

**Comment by exectails** [comment]
I guess that's good enough to close this issue^^ Adding specialized warps for quests will be part of adding those quests. Thanks guys!
