### ISSUE TITLE
Equipment prices

### ISSUE THREAD

**Issue by exectails** [aura-project/melia#58]
While most normal items have fixed (sell) prices, equipment prices are calculated somehow. The client displays those calculated prices in the NPC shops, while the server uses the db value (0). We have to figure out how those prices are calculated, to make shops work properly.

**Comment by elfinlazz** [comment]
ies.ipf/statbase_weapon.ies
this file have various 'price per itemlv' table
price = table_value[ItemLv] * 0.2

**Comment by exectails** [comment]
How is it possible I missed this, having searched all data for "price"? Oh well. Thanks, that table looks correct.

**Comment by exectails** [comment]
PR: #64
