### ISSUE TITLE
Headless NPC

### ISSUE THREAD

**Issue by psyzerkski** [aura-project/melia#72]
this NPC is creepy lol
![screenshot_20160606_00001](https://cloud.githubusercontent.com/assets/12017317/15815829/3dd7cdee-2b84-11e6-95c4-de74669fa081.jpg)

**Comment by exectails** [comment]
Huh, now what happened there, @Hirasu?

**Comment by exectails** [comment]
Closing, as it doesn't appear to be an issue anymore. Might have been an outdated client.
