### ISSUE TITLE
how can i download melia

### ISSUE THREAD

**Issue by wacks** [aura-project/melia#73]
pls help i wanna play TOS

**Comment by Tachiorz** [comment]
If you wanna play - get the game for free at http://store.steampowered.com/app/372000/ and play.

**Comment by exectails** [comment]
Regarding the question in the title, "How to download Melia", you should take a look at our Wiki: https://github.com/aura-project/melia/wiki/Getting-started

**Comment by wacks** [comment]
Greetings Saviors!

We are temporarily limiting access to new players.

Please check our You can check the details of why we are doing so on
our official
website
<https://steamcommunity.com/linkfilter/?url=https://treeofsavior.com/news/?n=428>
for
more details.

As always, thank you for your continued support, love and enthusiasm for
Tree of Savior.

Sincerely,
IMC Staff

2016-06-18 22:35 GMT+08:00 exec <notifications@github.com>:
