### ISSUE TITLE
Help me please...

### ISSUE THREAD

**Issue by grandsfather** [aura-project/melia#79]
Hello, help me please with error in console...
![123](https://cloud.githubusercontent.com/assets/2787165/19663696/4b3bf5f8-9a67-11e6-8afb-328ca1d629b0.png)
P.S Last client

**Comment by grandsfather** [comment]
log from "Login"
26.10.2016 0:00:01 [Info] - Initializing database...
26.10.2016 0:00:01 [Info] - Checking for updates...
26.10.2016 0:00:01 [Info] - Loading data...
26.10.2016 0:00:01 [Info] -   done loading 65 entries from jobs.txt
26.10.2016 0:00:01 [Info] -   done loading 340 entries from maps.txt
26.10.2016 0:00:01 [Info] -   done loading 2 entries from servers.txt
26.10.2016 0:00:01 [Info] -   done loading 3 entries from barracks.txt
26.10.2016 0:00:01 [Info] -   done loading 2 entries from startingcities.txt
26.10.2016 0:00:01 [Status] - Server ready, listening on 0.0.0.0:2000.
26.10.2016 0:00:01 [Info] - Type 'help' for a list of console commands.
26.10.2016 0:00:35 [Info] - Connection established from 127.0.0.1:7053
26.10.2016 0:00:36 [Info] - User 'test' logged in.
26.10.2016 0:00:36 [Warning] - Packet size doesn't match packet table size. (op: BC_LOGINOK (0010), size: 121, expected: 129)
26.10.2016 0:00:36 [Debug] - PacketHandler: No handler found for '004B', CB_REQ_CHANNEL_TRAFFIC.
------------------------------------------------------------------------------
Op: 004B CB_REQ_CHANNEL_TRAFFIC, Size: 16 (Table: 14, Garbage: 2)
------------------------------------------------------------------------------
0000   4B 00 03 00 00 00 49 00  00 00 01 00 00 00 BB B1   K.....I.........
------------------------------------------------------------------------------
26.10.2016 0:00:37 [Debug] - PacketHandler: No handler found for '004B', CB_REQ_CHANNEL_TRAFFIC.
------------------------------------------------------------------------------
Op: 004B CB_REQ_CHANNEL_TRAFFIC, Size: 16 (Table: 14, Garbage: 2)
------------------------------------------------------------------------------
0000   4B 00 05 00 00 00 4F 00  00 00 01 00 00 00 55 F2   K.....O.......U.
------------------------------------------------------------------------------
26.10.2016 0:00:58 [Debug] - PacketHandler: No handler found for '004B', CB_REQ_CHANNEL_TRAFFIC.
------------------------------------------------------------------------------
Op: 004B CB_REQ_CHANNEL_TRAFFIC, Size: 16 (Table: 14, Garbage: 2)
------------------------------------------------------------------------------
0000   4B 00 08 00 00 00 42 00  00 00 01 00 00 00 E0 A5   K.....B.........
------------------------------------------------------------------------------
26.10.2016 0:01:04 [Debug] - PacketHandler: No handler found for '004B', CB_REQ_CHANNEL_TRAFFIC.
------------------------------------------------------------------------------
Op: 004B CB_REQ_CHANNEL_TRAFFIC, Size: 16 (Table: 14, Garbage: 2)
------------------------------------------------------------------------------
0000   4B 00 09 00 00 00 43 00  00 00 01 00 00 00 73 07   K.....C.......s.
------------------------------------------------------------------------------
26.10.2016 0:01:14 [Warning] - Packet size doesn't match packet table size. (op: BC_COMMANDER_CREATE (0014), size: 334, expected: 342)
26.10.2016 0:01:14 [Warning] - CB_COMMANDER_MOVE: User 'test' tried to move invalid character (255).
26.10.2016 0:01:22 [Debug] - PacketHandler: No handler found for '004B', CB_REQ_CHANNEL_TRAFFIC.
------------------------------------------------------------------------------
Op: 004B CB_REQ_CHANNEL_TRAFFIC, Size: 16 (Table: 14, Garbage: 2)
------------------------------------------------------------------------------
0000   4B 00 0E 00 00 00 44 00  00 00 01 00 00 00 E8 10   K.....D.........
------------------------------------------------------------------------------
26.10.2016 0:01:32 [Debug] - PacketHandler: No handler found for '004B', CB_REQ_CHANNEL_TRAFFIC.
------------------------------------------------------------------------------
Op: 004B CB_REQ_CHANNEL_TRAFFIC, Size: 16 (Table: 14, Garbage: 2)
------------------------------------------------------------------------------
0000   4B 00 0F 00 00 00 45 00  00 00 01 00 00 00 F8 A3   K.....E.........
------------------------------------------------------------------------------
26.10.2016 0:01:40 [Warning] - CB_COMMANDER_MOVE: User 'test' tried to move invalid character (255).
26.10.2016 0:01:42 [Warning] - Packet size doesn't match packet table size. (op: BC_COMMANDER_CREATE (0014), size: 334, expected: 342)
26.10.2016 0:01:50 [Debug] - PacketHandler: No handler found for '004B', CB_REQ_CHANNEL_TRAFFIC.
------------------------------------------------------------------------------
Op: 004B CB_REQ_CHANNEL_TRAFFIC, Size: 16 (Table: 14, Garbage: 2)
------------------------------------------------------------------------------
0000   4B 00 13 00 00 00 59 00  00 00 01 00 00 00 5A A4   K.....Y.......Z.
------------------------------------------------------------------------------
26.10.2016 0:01:53 [Debug] - PacketHandler: No handler found for '004B', CB_REQ_CHANNEL_TRAFFIC.
------------------------------------------------------------------------------
Op: 004B CB_REQ_CHANNEL_TRAFFIC, Size: 16 (Table: 14, Garbage: 2)
------------------------------------------------------------------------------
0000   4B 00 14 00 00 00 5F 00  00 00 00 00 00 00 7E 59   K....._.......~Y
------------------------------------------------------------------------------
26.10.2016 0:01:53 [Info] - Connection was closed from '127.0.0.1:7053'.

**Comment by exectails** [comment]
Melia is currently not compatible to the latest client, it has to be updated =/

**Comment by grandsfather** [comment]
github will be updated?

**Comment by exectails** [comment]
Hopefully, at some point =|

**Comment by grandsfather** [comment]
what client version for this emulator?

**Comment by exectails** [comment]
I don't know which exact version was the last one that was working, maybe someone else knows, but you would also have to revert some updates in the ops code.

**Comment by grandsfather** [comment]
Thank you :), I will wait for the update emulator
