### ISSUE TITLE
Frozen in Place Bug

### ISSUE THREAD

**Issue by Achrome1** [aura-project/melia#81]
There seems to be a skill casting issue  where I'm not quite sure how to pinpoint the causation of it, but I have a somewhat clear hypothesis on what causes it to happen, but no idea on how to replicate it consistently:
When casting magic or using any kind of skill, Occasionally what would happen is that the skill would finish loading, but be incapable of actuation and I'm constantly locked in place. Now, the only reason I notice when the issue happens is when casting magic, the spell would randomly cast twice within half a second from the 1st cast because the  casting sound effect plays twice along with a greyed out skill for about a split second.
My theory is that it might be considering that 1st skill cast as constantly continuing to cast and then it would never complete casting because instead of being dropped, its counted as an ongoing cast that will never finish because its constantly being casted. Its a very wild theory, but thats my closest guess as to what's happening here. Hopefully I'm somewhere right  on the track with that assumption if this is looked into.

**Comment by exectails** [comment]
Hi, thanks for the report. Could you check the ChannelServer.txt log file in the log folder to see if there are any errors, warnings, or debug messages around the time where this happened?

**Comment by Achrome1** [comment]
I've tried looking for the log folder in the main files, but I can't seem to quite figure out where it is.
Could you point me in the general directory to look in, please?

**Comment by exectails** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/5593920/20555781/12a3f15a-b164-11e6-80f9-19e20608a180.PNG)

**Comment by Achrome1** [comment]
I actually don't have any of those other folders on my actual game directory, so I'm not quite sure If I don't understand what I'm seeing or if I'm in the wrong folder looking.

**Comment by exectails** [comment]
That's the Aura folder, the server.

**Comment by Achrome1** [comment]
Now I'm completely confused. I did a full search of my hard drive and I don't really see the Aura folder, nor does looking in the Github show that folder either, so now I feel even more confused than before.
Sorry if I'm being difficult. Trying my hardest not to be an idiot.

**Comment by exectails** [comment]
Is it possible you're playing on someone else's server? In that case you would not have a folder with the server files^^ You would also not have the log files I'm looking for. That's okay, we'll just have to try replicate the issue.

**Comment by Achrome1** [comment]
Hehe, Yeah, I think, maybe. I didn't realize there were more than one server, actually.
To be honest, I don't have very many tips on how to replicate it, but it seems to happen rather randomly for when someone uses a skill. but not so often that its an over glaring issue. Although I've seen it mostly happen on ranged and magic, so that's my best guess on where to start.
On a sidenote, I've been thinking about doing video recordings to help out with the project in the event that some kind of new bug occurs and needs proof of existence to be further looked into. Would that be of any assistance to you in any event?

**Comment by exectails** [comment]
Video demonstrations of bugs could definitely be helpful, depending on the bug.

**Comment by sant0ro** [comment]
@Achrome1 what is really your issue.. Are you a server player? Or an owner of a server?

--
This repository it's about a ToS Emulator, not a specific server.

**Comment by exectails** [comment]
Oh wow, I just realized this is a *Melia* issue, not *Aura* =X @Achrome1 Did you actually get Melia so far that you were able to try to cast a skill, or was this supposed to go in the Aura issues?

**Comment by Achrome1** [comment]
Ah, Server player. 
Also, this was in Mabinogi-- I'm definitely certain its supposed to be on an Aura server. I wish I could have gotten my recording software working with Mabinogi so I could actually show this off, since it actually did happen again earlier yesterday, but I it didn't quite work out as I planned and didn't get to show.

**Comment by exectails** [comment]
I see, in that case I'm going to close this issue here, but we should repost it on the [Aura repo](https://github.com/aura-project/aura/).
