### ISSUE TITLE
Launcher and HTTPS host

### ISSUE THREAD

**Issue by exectails** [aura-project/melia#86]
Starting the client to connect to an unofficial server has always been a little bothersome, and it only got worse since the static config file is being accessed via SSL. We should create a simple launcher that players can use, and a public host for the file, so we don't have to worry about SSL on the client side anymore.

I'm thinking about a simple program that takes an IP and a port, sets up an internal web server for the serverlist, and just uses a public file for the static config. Then it temporarily replaces the client.xml, to make the client connect there.

I've basically written the code for it already, for Zemyna, I'd just have to slap a nice UI onto it, and upload the config file somewhere.

This will then also make the respective files on the web server obsolete, and in turn, potentially, the entire web server, because in production users will most likely use their own servers.

**Comment by exectails** [comment]
Maybe we could actually host the conf file on GitHub, a quick test with the GH pages shows that the client takes one hosted on here just fine, and the [traffic limitations](https://help.github.com/articles/what-is-github-pages/#usage-limits) should never become a problem for such a small text file.

**Comment by celophi** [comment]
Creating a launcher would be ideal. I'm not so certain about hosting a configuration file on a third party site just so that we can work around the SSL issues. This is another setup step that Melia users would need to figure out (even if it is simple for us). 

Here are the issues:
- What if Github is down?
- What if I want to run Melia without an internet connection? (or an intermittent one)
- What if I don't like Github as my provider or it isn't available in my country?

Other than this small issue, I would support a custom launcher for the game.

**Comment by exectails** [comment]
>This is another setup step that Melia users would need to figure out

I don't understand. I imagine the GitHub URL to be the default for the launcher, but for it to be configurable of course, so you can use your own server instead for example. The goal for the launcher would be to be plug and play, put it into your TOS folder, start it, type in the IP and port, and you're a go.

You bring up good points with the potential issues with the internet and third-party services, but between that and people having to set up their own SSL servers, I imagine it's the lesser of two evils. It seems much less likely for GitHub to be down for prolonged periods of time, than for users to have trouble with SSL.

I was just thinking that GitHub might be a nice default, because that way we have the data where the repos for Melia and the launcher are as well, and as a professional service it has a rather high up-time, while being free for us.

>The game client itself has an entire HTTP browser

Oh, I didn't know that yet. Do any actual game features use that browser? In Mabinogi there were actually quite a few features that ran exclusively in a browser window, that's the reason I even wrote those web server libs, because we needed them there.

**Comment by celophi** [comment]
> Do any actual game features use that browser?

Aside from notifying users of new updates, I'm not sure. It seems to be more used for NXP/TP related things and for IMC when they need to debug something.

> lesser of two evils
Possibly. I think that we could go forward with that idea and make very sure to point out how to configure it in the wiki.

**Comment by exectails** [comment]
It would just be an easy way for people to start the client locally anyway, I imagine in production users of Melia would not use it, or our web server for that matter, but deploy their own, incl. properly customized XML file.

**Comment by celophi** [comment]
If a launcher is created, I think it would be a nice idea to support some of the command line arguments that the client accepts other than just `-SERVICE`.

**Comment by exectails** [comment]
Sure, I didn't know there were other parameters yet, just taking a look at them. Kinda interesting "-HEADROTATEOFF", "-DEV", hm, "-READBYXML", wonder what that one does.

The easiest solution would be a simple text field where the user can specify additional arguments of course, but depending on the arguments we might be able to make that more comfortable. All arguments I've seen looked like toggles, so we could create checkboxes.

**Comment by celophi** [comment]
> HEADROTATEOFF", "-DEV", hm, "-READBYXML", wonder what that one does.

I know what they do. I can write a document on it if you'd like.

**Comment by exectails** [comment]
Documenting them would be useful if we want to support them^^ We could give the wiki some love.

**Comment by exectails** [comment]
Now that the client apparently *doesn't* need HTTPS anymore again, I guess we can kind of shelve this for the moment. If all you have to do is replace the client.xml, or rather two strings within it, our time is probably better spent elsewhere, than writing and maintaining a launcher. I'll close this for now, and we can revisit it at some point.

Maybe someone from the community wants to give it a try, if so, please go ahead. If you want to discuss it, leave a comment here and I'll reopen the issue.
