### ISSUE TITLE
C# 6

### ISSUE THREAD

**Issue by exectails** [aura-project/melia#93]
Since I'm always trying to make my applications to be as simple to set up and use as possible, I put off using C# 6 features, because up until Debian 8 (Jessie), my distribution of choice, the default Mono version was 3.X, which didn't support C# 6. This would've made it "harder" for users to compile Melia on Debian, requiring them to get a newer version from somewhere else.

Usually in such cases people would tell me to make that the user's problem anyway, but now that Debian 9 is out, which uses Mono 4, I can't think of much of a reason to wait anymore. Unless someone can think of anything, I think it's safe to start to enjoy C# 6 in Melia.

**Comment by celophi** [comment]
If the transition to C# 6 is something to be done, are there any stylistic changes that we should adopt? Particularly the one that I find the most obvious would be string interpolation compared to using `string.format`.

**Comment by exectails** [comment]
Personally I see string interpolation more as an alternative to manual concatenation than `string.Format`, because for the latter there are still situations where you *need* it, like localization, and its strings will always be a little cleaner than both interpolation and concatenation. That being said, yes, I believe we should certainly start using it wherever it makes sense.

**Comment by exectails** [comment]
It's probably safe to assume that nobody will oppose this, so I think we should just start enjoying C# 6.

**Comment by exectails** [comment]
I just realized that most features I was looking forward to are actually C# *7*, not 6 o,o That would require Mono 5. Let's make that the new requirement, getting a newer version of Mono is simple enough really.
